[styles.document.colors]
background_color = [0x1e, 0x1e, 0x2e]
text_color = [0xcd, 0xd6, 0xf4]
link_color = [0x89, 0xb4, 0xfa]
pre_color = [0x94, 0xe2, 0xd5]
header1_color = [0xf5, 0xe0, 0xdc]
header2_color = [0xf5, 0xc2, 0xe7]
header3_color = [0xcb, 0xa6, 0xf7]
quote_color = [0xa6, 0xe3, 0xa1]
list_item_color = [0x74, 0xc7, 0xec]

[pki]
client_certificate_path = "/Users/hedy/certkey.pem"
