#!/usr/bin/env bash

PATH=~/bin:$PATH

setpaths() {
	fish -c 'set -Ux fish_user_paths $fish_user_paths '"$(parse_addpath)"
}

if ! command -v fish &> /dev/null; then
	echo "I'm sorry but I can't help you install fish"
	echo "Please install fish before running this script lol"
	exit 1
fi

echo "Setting up fish_user_paths..."
fish -c 'set -Ux fish_user_paths' # clear the variable first
setpaths
echo "done"

echo Maybe add ~/local/share/man to manpath but I forgot how as of writing

# env
echo "Generating ~/.exportenvs.fish"
~/dotscripts/gen/fish-exportenvs > /dev/null

# TODO have a better check for omf existence (command -v doesnt work)
# Although omf does this same check lol
if [ ! -d ~/.local/share/omf ]; then
	echo "Installing oh my fish"
	curl -L https://get.oh-my.fish | fish
	echo "Installing oh my fish packages"
	omf install
	echo done
fi
