#!/usr/bin/env bash
#
# This script is meant to support both first time setup as well as refreshing
# the ENV later on

PATH=~/bin:$PATH

if ! command -v fish &> /dev/null; then
	echo "I'm sorry but I can't help you install fish"
	echo "Please install fish before running this script lol"
	exit 1
fi

echo "Setting up fish_user_paths..."
fish -c "set -Ux fish_user_paths $(~/dotscripts/convert/addpath ' ')"
echo "done"

echo Maybe add ~/local/share/man to manpath but I forgot how as of writing

# env
echo "Refreshing generated fish configs"
~/dotscripts/gen/fish > /dev/null
echo -n source ~/.exportenvs.fish | pbcopy
echo PLEASE DO: source ~/.exportenvs.fish '(copied to clipboard)'

# TODO have a better check for omf existence (command -v doesnt work)
# Although omf does this same check lol
if [ ! -d ~/.local/share/omf ]; then
	echo "Installing oh my fish"
	curl -L https://get.oh-my.fish | fish
	echo "Installing oh my fish packages"
	omf install
	echo done
fi
