#!/usr/bin/env bash

if ! command -v nvim &> /dev/null; then
    echo "ERROR: nvim not found"
    exit
fi

cat <<END
I no longer use vim-plug. Lazy.nvim is bootstrapped at startup!

Reminders:

Treesitter:
- If there are errors for build, might wanna check C/C++ toolchain version

LSP
- Might need nvm
- Install clients listed in plugins/lsp.lua

Lint (optional)
- See plugins/lint.lua

DAP (optional)
- Set up virtualenv named debugpy that installs debugpy, see plugins/dap.lua
END

# DEST=${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim"

# if ! [[ -f "$DEST" ]]; then
#     echo "installing vim-plug for nvim"
#     curl -fLo "$DEST" --create-dirs \
#            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#     echo "installing nvim plugins"
#     nvim +PlugInstall +qall
# else
#     echo "upgrading vim-plug and nvim plugins"
#     nvim +PlugUpgrade +PlugUpdate +qall
# fi
