#!/usr/bin/env bash

if ! command -v nvim &> /dev/null; then
    echo "ERROR: nvim not found"
fi

DEST=${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim"

if ! [[ -f "$DEST" ]]; then
    echo "installing vim-plug for nvim"
    sh -c 'curl -fLo "$DEST" --create-dirs \
           https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    echo "installing nvim plugins"
    nvim +PlugInstall +qall
else
    echo "upgrading vim-plug and nvim plugins"
    nvim +PlugUpgrade +PlugUpdate +qall
fi
