(("default"    . ((user-emacs-directory   . "~/.config/emacsd")))
 ("doom"       . ((user-emacs-directory   . "~/.doomemacs")
				  (env . (
						  ("EMACSDIR"     . "~/.doomemacs")
						  ("DOOMDIR"      . "~/.config/doom")
						  )
					   )
				  )
  )
 )
