(("default"    . ((user-emacs-directory   . "~/.config/emacs")))
 ("test"       . ((user-emacs-directory   . "~/.config/emacstest")))
 ("doom"       . ((user-emacs-directory   . "~/.doomemacs")
                  (env . (("EMACSDIR"     . "~/.doomemacs")
                          ("DOOMDIR"      . "~/.config/doom"))))))
