source ~/.aliases

# Environment variables
# ~/.exportenvs.fish is generated by ~/dotscripts/gen/fish-exportenvs
if test -f ~/.exportenvs.fish
    source ~/.exportenvs.fish
end

if test -f ~/.config/fish/config_local.fish
	source ~/.config/fish/config_local.fish
end


# TODO: migrate .addpath and .exportenvs to direnv :D
if command -sq direnv > /dev/null
    direnv hook fish | source
end
