#!/usr/bin/env bash

echo "installing diff-so-fancy"
git clone https://github.com/so-fancy/diff-so-fancy ~/diffsofancy
chmod +x ~/diffsofancy/diff-so-fancy
ln -s ~/diffsofancy/diff-so-fancy ~/bin/
echo "installing vundle"
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo "installing vim plugins"
vim +PluginInstall
echo
echo "installing tmux package manager"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
echo "remember to hit <prefix> + I to install tmux plugins"
echo "done!"
