#!/usr/bin/env bash

if ! command -v fish &> /dev/null; then
	echo "I'm sorry but I can't help you install fish"
	echo "Please install fish before running this script lol"
	exit 1
fi

echo -n "Setting up fish_user_paths..."
cat <<END | fish
set -Ux fish_user_paths /home/hedy/bin /home/hedy/local/bin /home/hedy/.local/bin /home/hedy/go/bin $fish_user_paths
END
echo "done"

echo Maybe add ~/local/share/man to manpath but I forgot how as of writing

echo
echo "Installing oh my fish"
curl -L https://get.oh-my.fish | fish
echo "Installing oh my fish packages"
omf install
